Panic recover, y secure headers
FuenRob/PayWatcher pull request #11
Opened 2024-07-18 05:04 UTC by PatricioRios

Hola Roberto Morais, estuve viendo el directo en donde creabas este proyecto, y me anime a agregarle un par de middlewares, y a refactorizar algunas cosas, también agregue el identify con Hotmail al endpoint de login. Es mi segunda vez colaborando en un proyecto, y nose si puedes elegir qué cambios querés y cuáles no, cualquier cosa me avisas, saludos!

2024-07-18 07:30 UTC, FuenRob commented
¡Gracias por colaborar!

Se van a tener en cuenta todos lo cambios, porque la idea es aprender de tu aportación y si te parece para que aprendamos todos, veremos tu PR en directo y la comentaremos. Esto lo haremos en Agosto, ¿ok?

2024-07-22 22:54 UTC, PatricioRios commented
Vi en la documentación, que el "-" que estaba en el password y al parecer omite completamente el campo, tanto en la serialización como en la deserialización, yo lo quite porque me daba problemas en el momento de crear un usuario y autenticarme, talvez sea buena replantearse el uso de el field password, vi que hay una propiedad que se llama omitempty que hace que se ignore en caso de que el field sea vacío. Saludos!

2024-09-16 14:20 UTC, FuenRob requested changes

2024-09-16 14:20 UTC, FuenRob commented on .gitignore
> +.env
Si ignoramos el .env deberíamos crear un .env.example con datos dumy.

2024-09-16 14:20 UTC, FuenRob commented on .env
> -DB_PASS=root
Este cambio nos daría igual ya que a partir de ahora vamos a ignorar este fichero.

2024-09-16 14:20 UTC, FuenRob commented on controller/auth.go
> +
Si puedes quita este salto de línea, porfa

2024-09-16 14:20 UTC, FuenRob commented on controller/auth.go
> +	if strings.Contains(loginInput.Identity, "@") {
Para comprobar que es una email, podemos usar la función ParseAddress del paquete net/mail. Te dejo por aquí la documentación: https://pkg.go.dev/net/mail#ParseAddress

2024-10-08 11:47 UTC, FuenRob commented
Finalmente se han subido algunos de los ajustes de está PR en otra. Así que cerramos la PR. Muchas gracias Patricio.

2024-10-08 11:47 UTC, closed without merging

2024-10-08 16:42 UTC, PatricioRios commented
lamento no haber podido contribuir :c (estoy bastante ocupado con la uni), mucha suerte en el proyecto, talvez cuando tenga mas tiempo pueda hacer alguna contribibucion 🙂